# Generated by Django 4.0.5 on 2022-06-06 04:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, db_index=True, max_length=255, verbose_name='img'),
        ),
    ]
